### ISSUE TITLE
private key seed appears in log

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmcloud-otp#178]
per security best practices, we shouldn't log private keys.

This log from `HostCore.WebAssembly.Imports` dumps the seed field on error. The seed should be blanked out or replaced with "(omitted)" or "S(57 chars omitted)". A general solution is preferred rather than fixing the call in this location, for example, if whatever function converts the struct to json below could be overridden to accept a list of fields to mask, then it would apply to all debug or error logs. 

Alternate solutions:
- It's rare that the actual key is really needed for debugging, but If it's really important to confirm a specific key is present, then one of the following would be acceptable:
  - show the first 3 chars, compromising only a small portion of the bit length
   - compute a sha256 of the private key/seed and display that
   - enable key logging only with a special environment variable set, and by practice, only set that variable in test environments that share no keys with production and contain no sensitive data

```
15:02:29.186 [error] GenServer #PID<0.4774.0> terminating
** (FunctionClauseError) no function clause matching in HostCore.WebAssembly.Imports.authorize_call/1
    (host_core 0.50.0) lib/host_core/web_assembly/imports.ex:212: HostCore.WebAssembly.Imports.authorize_call(%{agent: #PID<0.4773.0>, authorized: false, binding: "default", claims: %{__struct__: HostCore.WasmCloud.Native.Claims, call_alias: nil, caps: [], issuer: "ABCEKIBKCOEN7K2FRRNACKON4OLM3FQ72ZYFAY22OJJSFOE6MQ6LEXF3", name: "pinger", public_key: "MDCX6E7RPUXSX5TJUD34CALXJJKV46MWJ2BUJQGWDDR3IYRJIWNUQ5PN", revision: 0, tags: [], version: "v0.1.0"}, namespace: "wasmcloud/examples/ponger", operation: "Ping", payload: <<129, 165, 118, 97, 108, 117, 101, 11>>, prefix: "default", seed: "SCAH4B44WHN7RJSGPRRI2DEVZENNNWEPXMG7BAE46PSSHMX4WSQZVGYW3M", source_actor: "MDCX6E7RPUXSX5TJUD34CALXJJKV46MWJ2BUJQGWDDR3IYRJIWNUQ5PN", state: %HostCore.Actors.ActorModule.State{api_version: 0, claims: %{__struct__: HostCore.WasmCloud.Native.Claims, call_alias: nil, caps: [], issuer: "ABCEKIBKCOEN7K2FRRNACKON4OLM3FQ72ZYFAY22OJJSFOE6MQ6LEXF3", name: "pinger", public_key: "MDCX6E7RPUXSX5TJUD34CALXJJKV46MWJ2BUJQGWDDR3IYRJIWNUQ5PN", revision: 0, tags: [], version: "v0.1.0"}, guest_error: nil, guest_request: nil, guest_response: nil, host_error: nil, host_response: nil, instance: #PID<0.4774.0>, instance_id: "6f30bac0-6c4d-42bc-976e-bb01cb8939fb", invocation: %HostCore.Actors.ActorModule.Invocation{operation: "HandleRequest", payload: <<133, 171, 113, 117, 101, 114, 121, 83, 116, 114, 105, 110, 103, 160, 164, 112, 97, 116, 104, 161, 47, 166, 109, 101, 116, 104, 111, ...>>}, ociref: "", subscription: 9}, target: {:actor, "MBMOM2EZZICFYM4KATRMH2JUO5QWE3YWCHGFZVRQQ2SQI4I5BKWIGMBS", "wasmbus.rpc.default.MBMOM2EZZICFYM4KATRMH2JUO5QWE3YWCHGFZVRQQ2SQI4I5BKWIGMBS"}, verified: true})
    (host_core 0.50.0) lib/host_core/web_assembly/imports.ex:144: HostCore.WebAssembly.Imports.host_call/11
    (wasmex 0.5.0) lib/wasmex.ex:339: Wasmex.handle_info/2
    (stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:invoke_callback, "wapc", "__host_call", %{memory: #Reference<0.508212900.3147431936.143714>}, [1056245, 7, 1056252, 25, 1056277, 4, 1114376, 8], #Reference<0.508212900.3147431936.143713>}
State: %{imports: %{"wapc" => %{"__console_log" => {:fn, [:i32, :i32], [], #Function<14.90078472/3 in HostCore.WebAssembly.Imports.wapc_imports/1>}, "__guest_error" => {:fn, [:i32, :i32], [], #Function<19.90078472/3 in HostCore.WebAssembly.Imports.wapc_imports/1>}, "__guest_request" => {:fn, [:i32, :i32], [], #Function<15.90078472/3 in HostCore.WebAssembly.Imports.wapc_imports/1>}, "__guest_response" => {:fn, [:i32, :i32], [], #Function<18.90078472/3 in HostCore.WebAssembly.Imports.wapc_imports/1>}, "__host_call" => {:fn, [:i32, :i32, :i32, :i32, :i32, :i32, :i32, :i32], [:i32], #Function<13.90078472/9 in HostCore.WebAssembly.Imports.wapc_imports/1>}, "__host_error" => {:fn, [:i32], [], #Function<20.90078472/2 in HostCore.WebAssembly.Imports.wapc_imports/1>}, "__host_error_len" => {:fn, [], [:i32], #Function<21.90078472/1 in HostCore.WebAssembly.Imports.wapc_imports/1>}, "__host_response" => {:fn, [:i32], [], #Function<16.90078472/2 in HostCore.WebAssembly.Imports.wapc_imports/1>}, "__host_response_len" => {:fn, [], [:i32], #Function<17.90078472/1 in HostCore.WebAssembly.Imports.wapc_imports/1>}}, "wasmbus" => %{"__console_log" => {:fn, [:i32, :i32], [], #Function<23.90078472/3 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}, "__guest_error" => {:fn, [:i32, :i32], [], #Function<28.90078472/3 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}, "__guest_request" => {:fn, [:i32, :i32], [], #Function<24.90078472/3 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}, "__guest_response" => {:fn, [:i32, :i32], [], #Function<27.90078472/3 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}, "__host_call" => {:fn, [:i32, :i32, :i32, :i32, :i32, :i32, :i32, :i32], [:i32], #Function<22.90078472/9 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}, "__host_error" => {:fn, [:i32], [], #Function<29.90078472/2 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}, "__host_error_len" => {:fn, [], [:i32], #Function<30.90078472/1 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}, "__host_response" => {:fn, [:i32], [], #Function<25.90078472/2 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}, "__host_response_len" => {:fn, [], [:i32], #Function<26.90078472/1 in HostCore.WebAssembly.Imports.wasmbus_imports/1>}}}, instance: #Wasmex.Instance<#Reference<0.508212900.3147300865.155272>>}
```

**Comment by stevelr** [comment]
In production, state is never logged. Not a bug.
