### ISSUE TITLE
[BUG] Hotwatch terminate fails with a case mismatch

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#466]
**Describe the bug**

When trying to hotwatch an actor as of `0.55.1`, it fails with an error terminating the actor. This is likely just a mismatch on handling the control interface response for an actor, so this is a great first issue for someone looking at the elixir codebase who wants to handle the `:ignore` condition.
```
08:13:03.629 [error] GenServer :actor_watcher terminating
** (MatchError) no match of right hand side value: :ignore
    (wasmcloud_host 0.55.1) lib/wasmcloud_host/actor_watcher.ex:90: WasmcloudHost.ActorWatcher.handle_call/3
    (stdlib 3.17.2) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.17.2) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.2485.0>): {:hotwatch_actor, "/tmp/chat/chat/chat-actor/build/chat_actor_s.wasm", 1}
08:13:03.630 [error] GenServer #PID<0.2485.0> terminating
** (stop) exited in: GenServer.call(:actor_watcher, {:hotwatch_actor, "/tmp/chat/chat/chat-actor/build/chat_actor_s.wasm", 1}, 60000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: :ignore
            (wasmcloud_host 0.55.1) lib/wasmcloud_host/actor_watcher.ex:90: WasmcloudHost.ActorWatcher.handle_call/3
            (stdlib 3.17.2) gen_server.erl:721: :gen_server.try_handle_call/4
            (stdlib 3.17.2) gen_server.erl:750: :gen_server.handle_msg/6
            (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.13.4) lib/gen_server.ex:1030: GenServer.call/3
    (wasmcloud_host 0.55.1) lib/wasmcloud_host_web/live/components/start_actor_component.ex:69: StartActorComponent.handle_event/3
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/channel.ex:553: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 0.4.3) /Users/runner/work/wasmcloud-otp/wasmcloud-otp/wasmcloud_host/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:199: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/channel.ex:483: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17.2) gen_server.erl:771: :gen_server.handle_msg/6
```

**To Reproduce**

1. Hotwatch an actor
1. See error

**Expected behavior**

**Environment (please complete the following information)**
 - OS: [e.g. Linux, MacOS, Windows] Macos
 - Arch: [e.g. x86_64, aarch64] aarch64
 - wasmCloud Version: [e.g. 0.51.0] 0.55.1

**Additional context**

I was using `wash up` to launch the host

**Comment by brooksmtownsend** [comment]
I believe this is now resolved
