### ISSUE TITLE
[BUG] Hotwatching does not work with burrito release

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#628]
**Describe the bug**

On v0.63.0, when I try to hotwatch an actor, it fails with an error. Effectively, before, there was a `mac_listener` file in the library files but now it seems to be missing.
```
12:15:48.878 [error] Can't find executable `mac_listener`
12:15:48.879 [error] registered_name=actor_watcher GenServer :actor_watcher terminating
** (MatchError) no match of right hand side value: :ignore
    (wasmcloud_host 0.63.0) lib/wasmcloud_host/actor_watcher.ex:97: WasmcloudHost.ActorWatcher.handle_call/3
    (stdlib 4.3.1) gen_server.erl:1149: :gen_server.try_handle_call/4
    (stdlib 4.3.1) gen_server.erl:1178: :gen_server.handle_msg/6
    (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.553.0>): {:hotwatch_actor, "/Users/brooks/github.com/brooksmtownsend/wadice/build/wadice_s.wasm", 1, "NCD5XQPRD4OJBGNMBMWQKW
JU7YHFW2TOMYEXRHXQRO4SOYDPQDTHCJO6"}
12:15:48.902 [error] GenServer #PID<0.553.0> terminating
** (stop) exited in: GenServer.call(:actor_watcher, {:hotwatch_actor, "/Users/brooks/github.com/brooksmtownsend/wadice/build/wadice_s.wasm", 1, "NCD5X
QPRD4OJBGNMBMWQKWJU7YHFW2TOMYEXRHXQRO4SOYDPQDTHCJO6"}, 60000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: :ignore
            (wasmcloud_host 0.63.0) lib/wasmcloud_host/actor_watcher.ex:97: WasmcloudHost.ActorWatcher.handle_call/3
            (stdlib 4.3.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.3.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.4) lib/gen_server.ex:1038: GenServer.call/3
    (wasmcloud_host 0.63.0) lib/wasmcloud_host_web/live/components/start_actor_component.ex:80: StartActorComponent.handle_event/3
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/channel.ex:553: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 0.4.3) /build/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:199: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/channel.ex:483: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.3.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1) gen_server.erl:1200: :gen_server.handle_msg/6
```

Looking into the burrito, it looks like we're packaging an `exe` for inotify instead of the `mac_listener` like Elixir expects

v0.62.1:
```
➜ fd mac_listener
lib/file_system-0.2.10/priv/mac_listener
```

v0.63.0:
```
~/Library/Application Support/.burrito/wasmcloud_host_erts-13.2.1_0.63.0/lib/file_system-0.2.10/priv ➜ ll
Permissions Size User   Date Modified Name
.rw-r--r--@  15k brooks 17 May 10:57  inotifywait.exe
```

**To Reproduce**

1. Run v0.63 of the host
2. Try to hotwatch an actor
3. Fails, see console for error

**Expected behavior**

**Environment (please complete the following information)**
 - OS: [e.g. Linux, MacOS, Windows] MacOS
 - Arch: [e.g. x86_64, aarch64] aarch64
 - wasmCloud Version: [e.g. 0.51.0] v0.63.0

**Additional context**

I'm unsure if this affects Windows or Linux

**Comment by brooksmtownsend** [comment]
still bug

**Comment by connorsmith256** [comment]
Since hot-watching isn't a feature of the new host, are you okay if we close this one @brooksmtownsend ?

**Comment by brooksmtownsend** [comment]
@connorsmith256 yep! This is definitely addressed by the `wash dev` command
